seed: 1
bls-verify: false
verify-proof-of-possession: false
bls-sign: false
genesis-time: 600
peers:
  - count: 8
    validator: true
    systemTimeShift: 0
    wireInboundDelay: 0
    wireOutboundDelay: 0
  - count: 1
    validator: false
