depositContractParameters:
  DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000
  DEPOSIT_CONTRACT_TREE_DEPTH: 32
honestValidatorParameters:
  ETH1_FOLLOW_DISTANCE: 1024
initialValues:
  GENESIS_FORK_VERSION: 0
  GENESIS_SLOT: 524288
  GENESIS_START_SHARD: 0
  FAR_FUTURE_EPOCH: 18446744073709551615
  ZERO_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
  EMPTY_SIGNATURE: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  BLS_WITHDRAWAL_PREFIX_BYTE: 0x00
maxOperationsPerBlock:
  MAX_PROPOSER_SLASHINGS: 16
  MAX_ATTESTER_SLASHINGS: 1
  MAX_ATTESTATIONS: 128
  MAX_DEPOSITS: 16
  MAX_VOLUNTARY_EXITS: 16
  MAX_TRANSFERS: 16
miscParameters:
  SHARD_COUNT: 1024
  TARGET_COMMITTEE_SIZE: 128
  MAX_BALANCE_CHURN_QUOTIENT: 32
  BEACON_CHAIN_SHARD_NUMBER: 18446744073709551615
  MAX_INDICES_PER_SLASHABLE_VOTE: 4096
  MAX_EXIT_DEQUEUES_PER_EPOCH: 4
gweiValues:
  MIN_DEPOSIT_AMOUNT: 1000000000
  MAX_DEPOSIT_AMOUNT: 32000000000
  FORK_CHOICE_BALANCE_INCREMENT: 1000000000
  EJECTION_BALANCE: 16000000000
rewardAndPenaltyQuotients:
  BASE_REWARD_QUOTIENT: 1024
  WHISTLEBLOWER_REWARD_QUOTIENT: 512
  ATTESTATION_INCLUSION_REWARD_QUOTIENT: 8
  INACTIVITY_PENALTY_QUOTIENT: 16777216
  MIN_PENALTY_QUOTIENT: 32
stateListLengths:
  LATEST_BLOCK_ROOTS_LENGTH: 8192
  LATEST_RANDAO_MIXES_LENGTH: 8192
  LATEST_ACTIVE_INDEX_ROOTS_LENGTH: 8192
  LATEST_SLASHED_EXIT_LENGTH: 8192
timeParameters:
  SECONDS_PER_SLOT: 6
  MIN_ATTESTATION_INCLUSION_DELAY: 4
  SLOTS_PER_EPOCH: 64
  MIN_SEED_LOOKAHEAD: 1
  ACTIVATION_EXIT_DELAY: 4
  EPOCHS_PER_ETH1_VOTING_PERIOD: 16
  MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
